services:
  strapi:
    build:
      context: ./build-context
      args:
        - STRAPI_VERSION=${STRAPI_VERSION:-3.6.8}
    image: local-strapi
    restart: unless-stopped
    tty: true
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
    volumes:
      - ./app:/srv/app
    ports:
      - target: 1337
        published: ${PORT:-1337}
        protocol: tcp
        mode: host
    env_file: .env
